# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOS24' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOS24

  pod 'Alamofire'

  target 'SOS24Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SOS24UITests' do
    # Pods for testing
  end

end
